name: Testing Deployment
on:
  push:
    branches: ['master']
  pull_request:
    types: [labeled, unlabeled, synchronize, closed, reopened]
jobs:
  call-deployment:
    uses: ilb/iconicactions/.github/workflows/deployment.yml@main
    secrets: inherit
    with:
      DOMAIN: ${{ github.repository_owner }}.icncd.ru
